// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzspprxfmrgctskuhqyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6c3BwcnhmbXJnY3Rza3VocXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1Mzk1OTEsImV4cCI6MjA2MzExNTU5MX0.2QZz-yj1yqJnnW9pLGcsqWIti7C_vR8UGj5YHJHchsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});